### ISSUE TITLE
CMD in Dockerfile

### ISSUE THREAD

**Issue by julienlim** [container-images/memcached#1]
Are there any plans to include the following CMD (switches for memcached) in the Dockerfile?

E.g. -m <memory_to-use> -vv

CACHE_SIZE appears to be similar to the -m switch, but I think that may have been for older releases of memcached.

-vv is for printing out errors and warnings, client commands and responses

Reason I mention this is that I see that FeedHenry and 3scale use these switches.

**Comment by phracek** [comment]
I would prefer to create a Pull Request.
I will test it later on and merge it.

-vv make sense definitely.

**Comment by TomasTomecek** [comment]
@phracek wouldn't the `-vv` switch be the same thing as `DEBUG_MODE`?

Is `CACHE_SIZE` actually working? I can't see supporting code processing that variable. Or is it internal variable of memcached?

**Comment by phracek** [comment]
@TomasTomecek yeah, make sense.

CACHE_SIZE is part if /etc/sysconfig/memcached. The PR is prepared a bit.
There are several other requirements. I hope I will incorporate it till end of this week.
Please be patient. Thx

**Comment by phracek** [comment]
The PR #9 should solve it.
