### ISSUE TITLE
polish templating

### ISSUE THREAD

**Issue by TomasTomecek** [container-images/memcached#11]
There are still some values which should be templated:

* [repository name](https://github.com/container-images/memcached/commit/843c46fa8fbdebcde841644b10e2604d0ebfe28f#diff-f75c3a9c2c1793a4664908f3b1ac4512R20)
* [base image name](https://github.com/container-images/memcached/commit/843c46fa8fbdebcde841644b10e2604d0ebfe28f#diff-f75c3a9c2c1793a4664908f3b1ac4512L12)

**Comment by pkubatrh** [comment]
I guess this can now be closed. Edit: ... since the repository does not use distgen anymore.
